vim.keymap.set('n', '<leader>bb', '<cmd>Telescope buffers<CR>', { noremap = true, desc = 'select buffer' })
vim.keymap.set('n', '<leader>hv', '<cmd>Telescope help_tags<CR>', { noremap = true, desc = 'help' })
vim.keymap.set('n', "<leader>'", '<cmd>Telescope marks<CR>', { noremap = true, desc = 'marks' })
vim.keymap.set('n', '<leader>ljr', '<cmd>Telescope lsp_references<CR>', { noremap = true, desc = 'references' })
vim.keymap.set('n', '<leader>ss', '<cmd>Telescope live_grep<CR>', { noremap = true, desc = 'grep' })
