# Paths
typeset -U path
path=(/bin /sbin ~/.local/bin ~/bin
      ~/.cabal/bin
      ~/.gem/ruby/2.6.0/bin
      ~/.go/bin
      ~/.npm_global/bin/
      ~/bin/anaconda3/bin
      $path)

# key maps
setxkbmap -layout us,br -variant dvp, -option "grp:alt_space_toggle"
setxkbmap -option compose:102
xmodmap -e 'keycode 135 = Super_R'
xmodmap -e 'keycode 97 = Control_R'
