# Paths
PATH=$PATH:/bin
PATH=$PATH:/sbin
PATH=$PATH:$HOME/.local/bin
# Cabal path
PATH=$PATH:$HOME/.cabal/bin
# Gem path
PATH=$PATH:$HOME/.gem/ruby/2.3.0/bin/
PATH=$PATH:$HOME/.gem/ruby/2.4.0/bin/
# go path
PATH=$PATH:$HOME/.go/bin
# npm path
PATH=$PATH:/home/gabriel/.npm_global/bin/
# conda path
PATH=$PATH:/home/gabriel/bin/anaconda3/bin

# key maps
setxkbmap -layout us,br -variant dvp, -option "grp:alt_space_toggle"
setxkbmap -option compose:102
xmodmap -e 'keycode 135 = Super_R'
xmodmap -e 'keycode 97 = Control_R'